const games = [
  {
    name: 'Doom Eternal',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/782330/DOOM_Eternal/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/DoomEternal.jpg',
    alt: 'Doom Eternal image',
  },
  {
    name: 'Hollow Knight',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/367520/Hollow_Knight/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/HollowKnight.jpg',
    alt: 'Hollow Knight image',
  },
  {
    name: 'Ori and the Will of the Wisps',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/1057090/Ori_and_the_Will_of_the_Wisps/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/Ori.jpg',
    alt: 'Ori and the Will of the Wisps image',
  },
  {
    name: 'Potionomics',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/1874490/Potionomics/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/Potionomics.jpg',
    alt: 'Potionomics image',
  },
  {
    name: 'Satisfactory',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/526870/Satisfactory/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/Satisfactory.jpg',
    alt: 'Satisfactory image',
  },
  {
    name: 'Skyrim',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/Skyrim.jpg',
    alt: 'Skyrim image',
  },
  {
    name: 'Stardew Valley',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/413150/Stardew_Valley/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/StardewValley.jpg',
    alt: 'Stardew Valley image',
  },
  {
    name: 'Steam World Dig 2',
    type: 'Singleplayer',
    website: 'https://store.steampowered.com/app/571310/SteamWorld_Dig_2/',
    about: 'About message',
    img: '../SiteDesign/Singleplayer/SteamWorldDig2.jpg',
    alt: 'Steam World Dig 2 image',
  },
  {
    name: 'Oldschool Runescape',
    type: 'Multiplayer',
    website: 'https://oldschool.runescape.com',
    about: 'About message',
    img: '../SiteDesign/Multiplayer/OldschoolRunescape.jpg',
    alt: 'Oldschool Runescape image',
  },
  {
    name: 'Halo Infinite',
    type: 'Multiplayer',
    website: 'https://store.steampowered.com/app/1240440/Halo_Infinite/',
    about: 'About message',
    img: '../SiteDesign/Multiplayer/HaloInfinite.jpg',
    alt: 'Halo Infinite image',
  },
  {
    name: 'League of Legends',
    type: 'Multiplayer',
    website: 'https://leagueoflegends.com',
    about: 'About message',
    img: '../SiteDesign/Multiplayer/LeagueofLegends.jpg',
    alt: 'League of Legends image',
  },
  {
    name: 'Minecraft',
    type: 'Multiplayer',
    website: 'https://minecraft.com',
    about: 'About message',
    img: '../SiteDesign/Multiplayer/Minecraft.jpg',
    alt: 'Minecraft image',
  },
  {
    name: 'Civilization 5',
    type: 'Multiplayer',
    website: 'https://store.steampowered.com/app/8930/Sid_Meiers_Civilization_V/',
    about: 'About message',
    img: '../SiteDesign/Multiplayer/Civ5.jpg',
    alt: 'Civilization 5 image',
  },
  {
    name: 'Dead by Daylight',
    type: 'Multiplayer',
    website: 'https://store.steampowered.com/app/381210/Dead_by_Daylight/',
    about: 'About message',
    img: '../SiteDesign/Multiplayer/DeadByDaylight.jpg',
    alt: 'Dead by Daylight image',
  },
  {
    name: 'Call of Duty Warzone 2.0',
    type: 'Multiplayer',
    website: 'https://us.shop.battle.net/en-us/product/call-of-duty-warzone-2',
    about: 'About message',
    img: '../SiteDesign/Multiplayer/Warzone.jpg',
    alt: 'Call of Duty Warzone 2.0 image',
  },

]

export default games;