const products = [
  {
    name: "Gala Apple",
    searchable: ["gala", "gala apples", "apple", "apples", "fruit", "produce"],
    image: "../cart/produce/apples.jpg",
    alt: "Apples image",
    price: 0.33,
    productQuantity: 10,
    byQuantity: "oz",
    weightBased: "Final cost based on weight",
  },
  {
    name: "Navel Oranges - 4 lb Bag",
    searchable: [
      "navel orange",
      "navel oranges",
      "orange",
      "oranges",
      "fruit",
      "produce",
    ],
    image: "../cart/produce/oranges.jpg",
    alt: "Navel Oranges image",
    price: 1.75,
    productQuantity: 4,
    byQuantity: "lb",
    weightBased: "",
  },
  {
    name: "Fresh Blueberries",
    searchable: ["blueberry", "blueberries", "fruit", "produce"],
    image: "../cart/produce/blueberries.jpg",
    alt: "Blueberries image",
    price: 0.31,
    productQuantity: 18,
    byQuantity: "oz",
    weightBased: "",
  },
  {
    name: "Yellow Banana - 1ct, 4 oz",
    searchable: ["banana", "bananas", "fruit", "produce"],
    image: "../cart/produce/bananas.jpg",
    alt: "Bananas image",
    price: 0.03,
    productQuantity: 4,
    byQuantity: "oz",
    weightBased: "Final cost based on weight",
  },
  {
    name: "Potato Chips",
    searchable: ["potato chips", "chips", "snack", "snacks"],
    image: "../cart/snacks/potato_chips.jpg",
    alt: "Potato Chips image",
    price: 0.26,
    productQuantity: 12,
    byQuantity: "oz",
    weightBased: "",
  },
  {
    name: "Pretzels - 16 oz",
    searchable: ["pretzel", "pretzels", "snack", "snacks"],
    image: "../cart/snacks/pretzels.jpg",
    alt: "Pretzels image",
    price: 0.22,
    productQuantity: 16,
    byQuantity: "oz",
    weightBased: "",
  },
  {
    name: "Reese's Pieces - 4 oz",
    searchable: ["reeses", "reese's", "candy", "snack", "snacks"],
    image: "../cart/snacks/reeses_pieces.jpg",
    alt: "Reese's Pieces image",
    price: 0.37,
    productQuantity: 4,
    byQuantity: "oz",
    weightBased: "",
  },
  {
    name: "Fresh Chicken - 1 lb",
    searchable: ["fresh chicken", "chicken", "meat", "poultry"],
    image: "../cart/grocery_image.jpg",
    alt: "Chicken image",
    price: 1.49,
    productQuantity: 1,
    byQuantity: "lb",
    weightBased: "Final cost based on weight",
  },
  {
    name: "Flank Steak",
    searchable: ["flank steak", "flank", "steak", "red meat", "meat"],
    image: "../cart/grocery_image.jpg",
    alt: "Steak image",
    price: 9.99,
    productQuantity: 1,
    byQuantity: "lb",
    weightBased: "Final cost based on weight",
  },
  {
    name: "Ground Turkey",
    searchable: ["ground turkey", "turkey", "meat"],
    image: "../cart/grocery_image.jpg",
    alt: "Ground Turkey image",
    price: 3.99,
    productQuantity: 2,
    byQuantity: "lb",
    weightBased: "Final cost based on weight",
  },
  // {
  //   name: '',
  //   searchable: [],
  //   image: '',
  //   alt: '',
  //   price: ,
  //   productQuantity: ,
  //   byQuantity: '',
  //   weightBased: 'Final cost based on weight'
  // },
  // {
  //   name: '',
  //   searchable: [],
  //   image: '',
  //   alt: '',
  //   price: ,
  //   productQuantity: ,
  //   byQuantity: '',
  //   weightBased: 'Final cost based on weight'
  // },
  // {
  //   name: '',
  //   searchable: [],
  //   image: '',
  //   alt: '',
  //   price: ,
  //   productQuantity: ,
  //   byQuantity: '',
  //   weightBased: 'Final cost based on weight'
  // },
  // {
  //   name: '',
  //   searchable: [],
  //   image: '',
  //   alt: '',
  //   price: ,
  //   productQuantity: ,
  //   byQuantity: '',
  //   weightBased: 'Final cost based on weight'
  // },
  // {
  //   name: '',
  //   searchable: [],
  //   image: '',
  //   alt: '',
  //   price: ,
  //   productQuantity: ,
  //   byQuantity: '',
  //   weightBased: 'Final cost based on weight'
  // },
  // {
  //   name: '',
  //   searchable: [],
  //   image: '',
  //   alt: '',
  //   price: ,
  //   productQuantity: ,
  //   byQuantity: '',
  //   weightBased: 'Final cost based on weight'
  // },
];

export default products;
